import { useEffect, useMemo, useState } from 'react';
import {
  getNotifications,
  notifyFeedbackSubmitted,
  notifyPaperSubmitted,
  notifyReviewCompleted,
  notifyReviewerAssigned,
  sendNotification,
} from '../api';

const initialForm = {
  actorUserId: '',
  recipientUserId: '',
  channel: 'SYSTEM_ALERT',
  actionType: '',
  message: '',
};

function formatDate(value) {
  if (!value) return 'N/A';
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? 'N/A' : parsed.toLocaleString();
}

export default function NotificationCenter() {
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [form, setForm] = useState(initialForm);
  const [eventForm, setEventForm] = useState({
    authorUserId: '',
    adminUserId: '',
    reviewerUserId: '',
    submissionId: '',
  });

  const loadNotifications = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await getNotifications();
      setNotifications(Array.isArray(response?.data) ? response.data : []);
    } catch (err) {
      setError(err?.response?.data?.message || err?.message || 'Unable to load notifications.');
      setNotifications([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, []);

  const summary = useMemo(() => {
    const sent = notifications.filter((item) => item?.status === 'SENT').length;
    const systems = notifications.filter((item) => item?.channel === 'SYSTEM_ALERT').length;
    return { total: notifications.length, sent, systems };
  }, [notifications]);

  const handleGenericSubmit = async (event) => {
    event.preventDefault();
    setSaving(true);
    setMessage('');
    try {
      await sendNotification(form);
      setForm(initialForm);
      setMessage('Notification sent successfully.');
      await loadNotifications();
    } catch (err) {
      setMessage(err?.response?.data?.message || err?.message || 'Failed to send notification.');
    } finally {
      setSaving(false);
    }
  };

  const fireEvent = async (action, payload) => {
    setSaving(true);
    setMessage('');
    try {
      await action(payload);
      setMessage('Event notification created successfully.');
      await loadNotifications();
    } catch (err) {
      setMessage(err?.response?.data?.message || err?.message || 'Failed to create event notification.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <div className="card metrics-header">
        <div>
          <h2>Notification Center</h2>
          <p className="metrics-subtitle">View Draftly notifications generated by paper, review, and workflow events.</p>
        </div>
        <div className="metrics-actions">
          <button className="btn btn-secondary" type="button" onClick={loadNotifications}>
            Refresh
          </button>
        </div>
      </div>

      <div className="metrics-grid">
        <div className="card metric-card">
          <p className="metric-label">Notifications</p>
          <p className="metric-value">{summary.total}</p>
        </div>
        <div className="card metric-card">
          <p className="metric-label">Delivered</p>
          <p className="metric-value">{summary.sent}</p>
        </div>
        <div className="card metric-card">
          <p className="metric-label">System Alerts</p>
          <p className="metric-value">{summary.systems}</p>
        </div>
      </div>

      {loading && <div className="card">Loading notifications...</div>}

      {!loading && error && (
        <div className="card flagged">
          <strong>Could not load notifications.</strong>
          <div>{error}</div>
        </div>
      )}

      {!loading && message && <div className="card issue">{message}</div>}

      <div className="analytics-two-col">
        <form className="card" onSubmit={handleGenericSubmit}>
          <h3>Create Notification</h3>
          <div className="form-group">
            <label htmlFor="actorUserId">Triggered By User ID</label>
            <input
              id="actorUserId"
              value={form.actorUserId}
              onChange={(event) => setForm({ ...form, actorUserId: event.target.value })}
              placeholder="admin1"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="recipientUserId">Recipient User ID</label>
            <input
              id="recipientUserId"
              value={form.recipientUserId}
              onChange={(event) => setForm({ ...form, recipientUserId: event.target.value })}
              placeholder="user42"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="channel">Channel</label>
            <select
              id="channel"
              value={form.channel}
              onChange={(event) => setForm({ ...form, channel: event.target.value })}
            >
              <option value="SYSTEM_ALERT">SYSTEM_ALERT</option>
              <option value="EMAIL">EMAIL</option>
              <option value="IN_APP">IN_APP</option>
            </select>
          </div>
          <div className="form-group">
            <label htmlFor="actionType">Action Type</label>
            <input
              id="actionType"
              value={form.actionType}
              onChange={(event) => setForm({ ...form, actionType: event.target.value })}
              placeholder="MANUAL_UPDATE"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="message">Message</label>
            <textarea
              id="message"
              value={form.message}
              onChange={(event) => setForm({ ...form, message: event.target.value })}
              placeholder="Draftly notification message"
              required
            />
          </div>
          <button className="btn btn-primary" type="submit" disabled={saving}>
            {saving ? 'Sending...' : 'Send Notification'}
          </button>

          <div style={{ marginTop: '1rem' }}>
            <h3>Workflow Events</h3>
            <div className="form-group">
              <label htmlFor="authorUserId">Author User ID</label>
              <input
                id="authorUserId"
                value={eventForm.authorUserId}
                onChange={(event) => setEventForm({ ...eventForm, authorUserId: event.target.value })}
                placeholder="author1"
              />
            </div>
            <div className="form-group">
              <label htmlFor="reviewerUserId">Reviewer User ID</label>
              <input
                id="reviewerUserId"
                value={eventForm.reviewerUserId}
                onChange={(event) => setEventForm({ ...eventForm, reviewerUserId: event.target.value })}
                placeholder="reviewer1"
              />
            </div>
            <div className="form-group">
              <label htmlFor="adminUserId">Admin User ID</label>
              <input
                id="adminUserId"
                value={eventForm.adminUserId}
                onChange={(event) => setEventForm({ ...eventForm, adminUserId: event.target.value })}
                placeholder="admin1"
              />
            </div>
            <div className="form-group">
              <label htmlFor="submissionId">Submission ID</label>
              <input
                id="submissionId"
                value={eventForm.submissionId}
                onChange={(event) => setEventForm({ ...eventForm, submissionId: event.target.value })}
                placeholder="submission-123"
              />
            </div>
            <div className="actions" style={{ flexWrap: 'wrap' }}>
              <button
                className="btn btn-secondary"
                type="button"
                disabled={saving}
                onClick={() => fireEvent(notifyPaperSubmitted, {
                  authorUserId: eventForm.authorUserId,
                  submissionId: eventForm.submissionId,
                })}
              >
                Paper Submitted
              </button>
              <button
                className="btn btn-secondary"
                type="button"
                disabled={saving}
                onClick={() => fireEvent(notifyReviewerAssigned, {
                  adminUserId: eventForm.adminUserId,
                  reviewerUserId: eventForm.reviewerUserId,
                  submissionId: eventForm.submissionId,
                })}
              >
                Reviewer Assigned
              </button>
              <button
                className="btn btn-secondary"
                type="button"
                disabled={saving}
                onClick={() => fireEvent(notifyFeedbackSubmitted, {
                  reviewerUserId: eventForm.reviewerUserId,
                  authorUserId: eventForm.authorUserId,
                  submissionId: eventForm.submissionId,
                })}
              >
                Feedback Submitted
              </button>
              <button
                className="btn btn-secondary"
                type="button"
                disabled={saving}
                onClick={() => fireEvent(notifyReviewCompleted, {
                  reviewerUserId: eventForm.reviewerUserId,
                  adminUserId: eventForm.adminUserId,
                  submissionId: eventForm.submissionId,
                })}
              >
                Review Completed
              </button>
            </div>
          </div>
        </form>

        <div className="card">
          <h3>Notification Log</h3>
          {notifications.length === 0 ? (
            <p>No notifications found yet.</p>
          ) : (
            <table>
              <thead>
                <tr>
                  <th>When</th>
                  <th>Action</th>
                  <th>Recipient</th>
                  <th>Channel</th>
                  <th>Status</th>
                  <th>Message</th>
                </tr>
              </thead>
              <tbody>
                {notifications.map((item) => (
                  <tr key={item.id}>
                    <td>{formatDate(item.deliveredAt || item.createdAt)}</td>
                    <td>{item.actionType || 'N/A'}</td>
                    <td>{item.recipientUserId || 'N/A'}</td>
                    <td>{item.channel || 'N/A'}</td>
                    <td>
                      <span className="badge badge-success">{item.status || 'N/A'}</span>
                    </td>
                    <td>{item.message || 'N/A'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </>
  );
}
